### ISSUE TITLE
Unreliable behaviour for `kt topic` on some topics

### ISSUE THREAD

**Issue by MarianoGappa** [fgeller/kt#31] opened 2016-08-29 22:35 UTC
On v9.2.0 (`a990512`) I'm getting this for some topic on a 0.10 cluster.

```
$ kt topic -brokers obfuscated:9092 -partitions --filter obfuscated.topic
$ kt topic -brokers obfuscated:9092 -partitions --filter obfuscated.topic
{"name":"obfuscated.topic","partitions":[{"id":0,"oldest":0,"newest":17}]}
$ kt topic -brokers obfuscated:9092 -partitions --filter obfuscated.topic
{"name":"obfuscated.topic","partitions":[{"id":0,"oldest":0,"newest":17}]}
$ kt topic -brokers obfuscated:9092 -partitions --filter obfuscated.topic
$
```

**Comment by fgeller** [comment] 2016-11-20 06:39
@MarianoGappa couldn't reproduce this -- can you reproduce it? if so, could you update kt (upgraded sarama on master branch) 
```
go get -u github.com/fgeller/kt
```

and then use the `-verbose` flag to see sarama's logs

```
kt topic -verbose -brokers obfuscated:9092 -partitions -filter obfuscated.topic
```

and report them here?

**Comment by fgeller** [comment] 2016-12-08 08:09
closing this for now - please re-open if you see it after upgrading to v10.0.0

**Closed by fgeller** 2016-12-08 08:09 UTC
