### ISSUE TITLE
Seeing escape char, if producer from kotlin

### ISSUE THREAD

**Issue by ssenthil416** [fgeller/kt#127] opened 2022-01-19 20:48 UTC
Hi team

We have experienced an issue with kt tool. 
We write to a topic from kotlin code and we use kt to view it. We see escape char like this.

>>>>>>>>
{
  "partition": 2,
  "offset": 1223,
  "key": null,
  "value": "{\\"user\\":\\"sundar\\",\\"book\\":\\" Alerts Test \\",\\"timestamp\\":\\"2022-01-19T16:18:27Z\\",\\"reason\\":\\"test Alerts\\"}",
  "timestamp": "2022-01-19T10:18:27.791-06:00"
}
>>>>>>>>>

But if we use the kafka-console-consumer.sh tool we are not seeing any escape char. 

Lets know is it problem on kt side or the library which we use in kotlin code

**Comment by ssenthil416** [comment] 2022-01-24 21:18
@fgeller please check now, I have update. you will see the "\" the escape char

**Comment by fgeller** [comment] 2022-03-03 07:05
:wave: 

that escape char looks correct to me, redacted version:
```json
{
"value": "{\"user\":\"sundar\",\"book\":\" Alerts Test \",\"timestamp\":\"2022-01-19T16:18:27Z\",\"reason\":\"test Alerts\"}",
}
```

it's a json payload that's contained in a string, so the double quotes need to be escaped. can you maybe tell me if this is causing any issues?

**Comment by fgeller** [comment] 2022-08-08 08:17
closing this optimistically, @ssenthil416 please re-open if the issue is still present and you have some more info -- thanks!

**Closed by fgeller** 2022-08-08 08:17 UTC
